//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyPlanner.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public long PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FriendlyName { get; set; }
        public int PersonTypeId { get; set; }
        public long EventId { get; set; }
        public Nullable<int> FavoriteDrinkId { get; set; }
    
        public virtual FavoriteDrink FavoriteDrink { get; set; }
        public virtual PartyEvent PartyEvent { get; set; }
        public virtual PersonType PersonType { get; set; }
    }
}
